# Generated by Django 2.1.2 on 2018-11-01 01:55

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCardSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Titulo da seção')),
                ('title_bold', models.CharField(blank=True, help_text='Este será a parta destacada em nergrito no titulo da seção.', max_length=50, verbose_name='Parte do titulo destacado (em negrito)')),
                ('description', models.CharField(max_length=250, verbose_name='Descrição')),
                ('active', models.BooleanField(verbose_name='Seção ativa?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Seção 'Sobre'",
                'verbose_name_plural': "Seções 'Sobre'",
            },
        ),
        migrations.CreateModel(
            name='AboutCardTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Este valor se refere ao nome do icone. Para ver a lista com os nomes visite o link: http://themes-lab.com/make-frontend/pages/elements/icons.html', max_length=200, verbose_name='Nome do ícone do tópico')),
                ('title', models.CharField(max_length=50, verbose_name='Título do tópico')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Descrição do tópico')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topics_set', to='core.AboutCardSection', verbose_name='Seção ao qual está relacionado')),
            ],
            options={
                'verbose_name': "Tópico para seção 'Sobre'",
                'verbose_name_plural': "Tópicos para seção 'Sobre'",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvantageTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Este valor se refere ao nome do icone. Para ver a lista com os nomes visite o link: http://themes-lab.com/make-frontend/pages/elements/icons.html', max_length=200, verbose_name='Nome do ícone do tópico')),
                ('title', models.CharField(max_length=50, verbose_name='Título do tópico')),
                ('description', models.CharField(max_length=250, verbose_name='Descrição')),
                ('active', models.BooleanField(blank=True, verbose_name='Slide ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vantagem',
                'verbose_name_plural': 'Vantagens',
            },
        ),
        migrations.CreateModel(
            name='BenefitSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo da seção')),
                ('description', models.CharField(max_length=250, verbose_name='Descrição')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Imagem principal')),
                ('active', models.BooleanField(verbose_name='Seção ativa?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Seção 'Benefício'",
                'verbose_name_plural': "Seções 'Benefício'",
            },
        ),
        migrations.CreateModel(
            name='BenefitTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Este valor se refere ao nome do icone. Para ver a lista com os nomes visite o link: http://themes-lab.com/make-frontend/pages/elements/icons.html', max_length=200, verbose_name='Nome do ícone do tópico')),
                ('title', models.CharField(max_length=50, verbose_name='Título do tópico')),
                ('description', models.CharField(max_length=250, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='benefit_set', to='core.BenefitSection', verbose_name='Seção ao qual está relacionado')),
            ],
            options={
                'verbose_name': "Tópico para seção 'Benefício'",
                'verbose_name_plural': "Tópicos para seção 'Benefício'",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlexSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_phrase', models.CharField(max_length=50, verbose_name='Primeira frase (menor)')),
                ('second_phrase', models.CharField(max_length=50, verbose_name='Segunda frase (em destaque)')),
                ('slide_image', models.ImageField(upload_to='slide_item/%Y/%m/%d/', verbose_name='Imagem do slide')),
                ('active', models.BooleanField(blank=True, verbose_name='Slide ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Slides',
            },
        ),
        migrations.CreateModel(
            name='HowItWorksSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo da seção')),
                ('title_bold', models.CharField(blank=True, help_text='Este será a parta destacada em nergrito no titulo da seção.', max_length=50, verbose_name='Parte do titulo destacado (em negrito)')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Imagem principal')),
                ('active', models.BooleanField(verbose_name='Seção ativa?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Seção 'Como Funciona'",
                'verbose_name_plural': "Seções 'Como Funciona'",
            },
        ),
        migrations.CreateModel(
            name='HowItWorksTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Este valor se refere ao nome do icone. Para ver a lista com os nomes visite o link: http://themes-lab.com/make-frontend/pages/elements/icons.html', max_length=200, verbose_name='Nome do ícone do tópico')),
                ('title', models.CharField(max_length=50, verbose_name='Título do tópico')),
                ('description', models.CharField(max_length=250, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='howitworks_set', to='core.HowItWorksSection', verbose_name='Seção ao qual está relacionado')),
            ],
            options={
                'verbose_name': "Tópico para seção 'Como Funciona'",
                'verbose_name_plural': "Tópicos para seção 'Como Funciona'",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=255, verbose_name='Nome do parceiro')),
                ('image', models.ImageField(upload_to='partners/icons/%y/%m', verbose_name='Imagem do parceiro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Tópico para seção 'Parceiros'",
                'verbose_name_plural': "Tópicos para seção 'Parceiros'",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnersSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('title_bold', models.CharField(blank=True, help_text='Este será a parta destacada em nergrito no titulo da seção.', max_length=50, verbose_name='Parte do titulo destacado (em negrito)')),
                ('text', ckeditor.fields.RichTextField(blank=True, verbose_name='Texto da seção')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Autor do texto (caso haja)')),
                ('active', models.BooleanField(verbose_name='Seção ativa?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Seção 'Parceiros'",
                'verbose_name_plural': "Seções 'Parceiros'",
            },
        ),
        migrations.AddField(
            model_name='partnericon',
            name='partner_section',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='partners_set', to='core.PartnersSection', verbose_name='Seção relacioada'),
        ),
    ]
