# Generated by Django 2.1.2 on 2018-11-01 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181101_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Título do tópico')),
                ('counter', models.CharField(max_length=50, verbose_name='Numero')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contador',
                'verbose_name_plural': 'Contadores',
            },
        ),
    ]
