# Generated by Django 2.1.2 on 2018-11-02 01:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_countersection'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('position', models.CharField(max_length=50, verbose_name='Cargo')),
                ('testimonial', ckeditor.fields.RichTextField(blank=True, verbose_name='Testimonial')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Imagem (Avatar)')),
                ('active', models.BooleanField(blank=True, verbose_name='Slide ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
    ]
